### ISSUE TITLE
Pr3: `leaves` está cerca...

### ISSUE THREAD

**Issue by fidel-ml** [NahuelMGithub/Estructura-de-Datos#10]
Fijate que al tratar de usar `agregarSiEsHoja` no está mirando si es hoja... Deberías usar algo como el `singularSi` de InPr.
Por otra parte, para llamar a `esHoja` estás rearmando algo que inmediatamente vas a desarmar. Por eso sería más interesante pasarle solamente las partes que necesitás para la pregunta, o preguntar directamente...

**Comment by NahuelMGithub** [comment]
Listo

**Comment by fidel-ml** [comment]
El nombre `esHoja` es raro, porque toma DOS árboles... Si lo mirás aislado, carece de sentido, porque no es eso lo que estás preguntando.
¿No lo podés descomponer en algo más elemental? ;)

**Comment by NahuelMGithub** [comment]
claro, lo que puedo hacer es:
` esHoja :: Tree a -> Bool
esHoja a = esVacio a ` 
Y por otro lado, en el leaves, en singunlaSi pregunto ambos  `esHoja a1 && esHpja a2`

**Comment by fidel-ml** [comment]
No. Es mejor si cambiás la pregunta para mirar otra cosa... ¿Qué cumple CADA subárbol de una hoja?

**Comment by NahuelMGithub** [comment]
ambos son `EmptyT`
