### ISSUE TITLE
Pr3: `eval` debería ser total, pero es parcial

### ISSUE THREAD

**Issue by fidel-ml** [NahuelMGithub/Estructura-de-Datos#12]
Faltan casos... MUCHOS casos... ¿Por qué el doble PM? RECURSIÓN ESTRUCTURAL

**Comment by NahuelMGithub** [comment]
Listo.

**Comment by NahuelMGithub** [comment]
listo.
Habia copiado mal del pdf

**Comment by fidel-ml** [comment]
Yo lo sigo viendo mal...

**Comment by NahuelMGithub** [comment]
no lo subí aún
Estoy contestando mientras corrijo, y despues subo todo.
