### ISSUE TITLE
Pr3: `simplificar` debería pensarse POR RECURSIÓN ESTRUCTURAL

### ISSUE THREAD

**Issue by fidel-ml** [NahuelMGithub/Estructura-de-Datos#13]
Confiá en la técnica Miyagui.

**Comment by NahuelMGithub** [comment]
lo hice ayer en la entrega
claramente al leer esto me doy cuenta que lo hice mal.

**Comment by NahuelMGithub** [comment]
creo que esta...

**Comment by fidel-ml** [comment]
La veo igual...

**Comment by fidel-ml** [comment]
¡¡¡No estás usando recursión!!!
Además, la auxiliar para el caso Neg es incorrecta, porque pierde Negs...

**Comment by NahuelMGithub** [comment]
listo
