### ISSUE TITLE
Pr4: `hayTesoroEn` tiene doble PM y código duplicado

### ISSUE THREAD

**Issue by fidel-ml** [NahuelMGithub/Estructura-de-Datos#15]
Los casos 1 y 2 hacen exactamente lo mismo.

**Comment by NahuelMGithub** [comment]
claro, yo lo había hecho para reutilizar el código de los ejercicios anteriores. Y en `hayTesoroEnCofre`  pide Cofre
mientras que en `hayTesoro` pide un Mapa, pero me devuelve info de cualquier parte. 
Así que lo corregí con una nueva subtarea
