### ISSUE TITLE
Pr5: el costo de `takeN` es incorrecto

### ISSUE THREAD

**Issue by fidel-ml** [NahuelMGithub/Estructura-de-Datos#25]
Siempre tenés que justificar los costos. Así como está es imposible entender dónde te equivocaste...

Pasa lo mismo con `partir`.

**Comment by NahuelMGithub** [comment]
Listos. los puse como lineales, dependietes del Int. ya que la otra operación es constante.

**Comment by fidel-ml** [comment]
Faltaría justificar en el código...
