### ISSUE TITLE
Pr5: en `Queue1`, `sinPrimerElemento` es incorrecta

### ISSUE THREAD

**Issue by fidel-ml** [NahuelMGithub/Estructura-de-Datos#32]
Básicamente, invierte el orden de los elementos de la cola... (Si estás segundo y te mandan al fondo, ¿no te enojarías? Eso hiciste con la pobre gente esperando... ;)).

**Comment by NahuelMGithub** [comment]
es que es la pizzeria de capusotto JAJAJA
Cuando llegué a este Issue, ya lo había resuelto. 
Porque resolviendo el issues 31 me econtré con este problema
