### ISSUE TITLE
Pr5: en `QueueConDosListas`, la operación `queue` usa otras operaciones de interfaz

### ISSUE THREAD

**Issue by fidel-ml** [NahuelMGithub/Estructura-de-Datos#34]
No es demasiado feliz depender de otras operaciones de interfaz. Siempre es mejor utilizar operaciones auxiliares internas sobre la representación, quizás utilizadas desde más de una función de interfaz...

**Comment by NahuelMGithub** [comment]
ah perfeto, yo pensé que era mejor reutilizar. 
Listo. ya la cambie
