### ISSUE TITLE
Pr2: en `seniorsEnProyectos` hay varios errores

### ISSUE THREAD

**Issue by fidel-ml** [NahuelMGithub/Estructura-de-Datos#5]
El primero es ¿para qué mirás la lista de proyectos por PM, si luego vas a usar una auxiliar que se encarga de ese caso?
Y el segundo es que no estás mirando los dev senior, sino todos los roles...

**Comment by NahuelMGithub** [comment]
Conulsta. 
Primero:  no entiendo, en sí hago RE sobre la lista de Roles. 
Segundo: seniorYParticipa separa los ROles que son Seniors.

**Comment by fidel-ml** [comment]
Primero: claro, pero la lista de roles es el 1er parámetro. ¿Para qué mirás el 2do?
Segundo: Claro, los senior, pero NO los DEVELOPER que son Senior...

**Comment by NahuelMGithub** [comment]
listo.
