### ISSUE TITLE
Pr2: la función `esSenior` tiene demasiadas responsabilidades

### ISSUE THREAD

**Issue by fidel-ml** [NahuelMGithub/Estructura-de-Datos#6]
Al hacer doble PM la estás recargando. Si estás mirando el Rol, no mirás sus componentes, sino que delegás en otras funciones auxiliares que corresponda...

**Comment by NahuelMGithub** [comment]
Listo.

**Comment by fidel-ml** [comment]
Mejora. Pero si en `seniorYParticipa` vas a usar una subtarea, ¿por qué hacer análisis de casos? LAS SUBTAREAS se encargan de los subcasos; solamente tenés que hacer eso si usás diferentes subtareas en los diferentes casos, pero no es lo que pasa acá...

**Comment by NahuelMGithub** [comment]
Tal vez no estoy entendiendo, peor el analisis de casos se refire a que seniorYParticipa  pregunta por lista []
y luego por (p:ps)
Eso es lo que está mal?
o que en  seniorYParticipa  r (p:ps) = ..... use dos subtareas ?

**Comment by fidel-ml** [comment]
Claro. ¿Para qué querés mirar si la lista es vacía o `(:)`, si después usás subtareas? 
Fijate además que no estás mirando nunca el primer proyecto, porque lo descartaste al hacer un PM innecesario.

**Comment by NahuelMGithub** [comment]
Listo., era simplemente sacar el primer caso (el de lista vacía, porque mi subtarea  perteneceProyecto ya mira eso)
