### ISSUE TITLE
Pr2: en `totalTrbajandoEn` estás mirando casos de más, por hacer doble PM

### ISSUE THREAD

**Issue by fidel-ml** [NahuelMGithub/Estructura-de-Datos#7]
¿Para qué mirar un parámetro del que se encarga una subtarea? El 2do caso es innecesario (y rompe la recursión estructural)

**Comment by NahuelMGithub** [comment]
Claro, no tenia sentido, orque si la sgunda lista es null la recursion se va a encargar de todos modos. 
Ya lo corregí
Viendolo así, en la funcion  seniorEnProyectos  me pasa lo mism. Verdad ?
seniorEnProyectos :: [Rol] -> [Proyecto] -> Int
seniorEnProyectos []     _      = 0
seniorEnProyectos (r:rs) []     = 0
seniorEnProyectos (r:rs) ps = unoSi (perteneceProyecto (proyectoDelRol r) ps )
                                    + seniorEnProyectos rs ps

**Comment by fidel-ml** [comment]
Exacto,
Ojo al nombre. Acabo de ver que tiene un typo.
