### ISSUE TITLE
Pr2: en la función `asignadosPorProyecto` estás repitiendo muchas veces cada proyecto...

### ISSUE THREAD

**Issue by fidel-ml** [NahuelMGithub/Estructura-de-Datos#8]
O sea, si un proyecto `p` particular aparece 3 veces, ponés 3 elementos `(p,3)` en la lista final, y esto no es feliz.
Además, estás recorriendo muchísimas veces todos los proyectos de la empresa, lo que no es muy bueno.
La idea es usar recursión estructural sobre los proyectos de la empresa...

**Comment by NahuelMGithub** [comment]
Lo soluciono con algun sin Repetir? 
asignadosPorProyecto (ConsEmpresa rs) = subRepetirDupla (rolesAsignados rs)

**Comment by fidel-ml** [comment]
No. Al hacer eso tenés que hacer 20mil pasadas para sacar los repetidos, y luego VOLVER a recorrer la empresa POR CADA UNO de los proyectos obtenidos, contando. Es MUCHO mejor pensar por recursión estructural... ¿Te suena?

**Comment by NahuelMGithub** [comment]
listo
