### ISSUE TITLE
Pr3: `alMenosNTesoros` trabaja de más

### ISSUE THREAD

**Issue by fidel-ml** [NahuelMGithub/Estructura-de-Datos#9]
Estás reemplazando una búsqueda por una totalización, y eso no es bueno. Lo vieron en InPr con la búsqueda del ancho de espadas: si tengo 10mil cartas, y el ancho está primero, si trato de contar los anchos tengo que mirar las 10mil cartas, pero puedo cortar apenas veo esa carta y no necesito mirarlas todas...

**Comment by NahuelMGithub** [comment]
listo. 
Hice una suerte de "acumulador"
pero no sé si es correcto eso.

**Comment by fidel-ml** [comment]
¿A qué llamás un "contador"? No es lo que tenés. 
De paso, te faltan casos.

**Comment by NahuelMGithub** [comment]
le digo "acumulador" al hecho de que voy restando  (dentro de la RE (n - totalDeTesoros obs )
No veo cuales casos faltan.

**Comment by fidel-ml** [comment]
No es un "acumulador" porque no acumula nada... Es el parámetro que te dice cuántos te falta encontrar...

Sobre los casos que faltan. ¿Cuántos constructores tiene `Camino`?

**Comment by NahuelMGithub** [comment]
me falto el tercer constructor!

**Comment by fidel-ml** [comment]
Es un error que parece pavo, pero en realidad muestra que no estás mirando la estructura antes que mirar el problema...
